services:
  db:
    image: postgres:13
    container_name: postgres-db-v1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: student
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - PrviNetwork
  cloudbeaver:
    image: dbeaver/cloudbeaver
    container_name: cloudbeaver_v1
    restart: always
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver-data:/opt/cloudbeaver/workspace
    networks:
      - PrviNetwork

volumes:
  postgres-data:
  cloudbeaver-data:

networks:
  PrviNetwork:
    external: true